# Generated by Django 4.1.2 on 2022-11-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='edad',
            field=models.IntegerField(default='0'),
        ),
    ]
