# Generated by Django 4.1.2 on 2022-11-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_app', '0004_alter_alumno_codigo_estudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='Materia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='seccion',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
