# Generated by Django 4.1.2 on 2022-11-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_app', '0005_alter_docente_materia_alter_docente_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Docente',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='seccion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
