# Generated by Django 4.1.2 on 2022-11-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_app', '0006_alter_alumno_docente_alter_alumno_seccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Docente',
            new_name='docente',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='codigo_estudiantes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='seccion',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
